// ─────────────────────────────────────────────────────────────────────────────
// products.js — Product catalogue & category list
// ─────────────────────────────────────────────────────────────────────────────
//
// HOW TO CUSTOMISE:
//  • Add or remove items from the `products` array below.
//  • Replace the `image` URL with a local path, e.g. "./assets/images/dragon.jpg"
//    or any direct image URL. Recommended image size: 600×600 px (square).
//  • Set `featured: true` to show a product in the "Popular Items" row.
//  • `oldPrice` is optional — leave it as `null` to hide the strikethrough price.
//  • `id` values must be unique positive integers.
//
// PLACEHOLDER IMAGES:
//  All images below use https://placehold.co — a free CDN-hosted placeholder
//  service. They will work on GitHub Pages with no setup needed.
//  Replace each URL with your own product photo when ready.
//
// ─────────────────────────────────────────────────────────────────────────────

export const products = [
  {
    id: 1,
    name: "Articulated Dragon",
    category: "Collectibles",
    price: 18.00,
    oldPrice: 22.00,
    rating: 4.9,
    reviewCount: 47,
    // Replace with: "./assets/images/dragon.jpg"
    image: "./assets/images/3dprinting-image1.png",
    description: "Fully articulated dragon with 30+ moving joints. Printed in one piece — no assembly, no glue. A showstopper.",
    featured: true,
  },
  {
    id: 2,
    name: "Flexi Lizard",
    category: "Fidgets",
    price: 9.00,
    oldPrice: null,
    rating: 4.8,
    reviewCount: 31,
    image: "https://placehold.co/600x600/1A2A1A/00C896?text=Lizard",
    description: "Satisfying flexible lizard with a smooth articulated spine. Great desk fidget and conversation piece.",
    featured: false,
  },
  {
    id: 3,
    name: "Custom Name Keychain",
    category: "Keychains",
    price: 6.00,
    oldPrice: null,
    rating: 5.0,
    reviewCount: 83,
    image: "https://placehold.co/600x600/1A1A2A/7C6FCD?text=Keychain",
    description: "Personalised keychain with any name or short word. Mention your preferred colour in the order notes.",
    featured: true,
  },
  {
    id: 4,
    name: "Modular Desk Organiser",
    category: "Desk Toys",
    price: 14.00,
    oldPrice: 18.00,
    rating: 4.7,
    reviewCount: 22,
    image: "https://placehold.co/600x600/221A0A/C8842A?text=Organiser",
    description: "Stackable desk organiser for pens, cables, and small items. Clean minimal design that fits any desk.",
    featured: false,
  },
  {
    id: 5,
    name: "Geometric Planter Pot",
    category: "Planters",
    price: 12.00,
    oldPrice: null,
    rating: 4.6,
    reviewCount: 19,
    image: "https://placehold.co/600x600/1A241A/4CAF50?text=Planter",
    description: "Low-poly geometric planter for small succulents or cacti. Drainage hole included. Multiple colours available.",
    featured: false,
  },
  {
    id: 6,
    name: "Adjustable Phone Stand",
    category: "Phone Stands",
    price: 8.00,
    oldPrice: 10.00,
    rating: 4.8,
    reviewCount: 56,
    image: "https://placehold.co/600x600/0A1E22/2A9DB5?text=Stand",
    description: "Sleek phone stand for desk use. Fits most phone sizes including cases. Great for video calls.",
    featured: true,
  },
  {
    id: 7,
    name: "Cable Management Clips (Set of 4)",
    category: "Home Decor",
    price: 5.00,
    oldPrice: null,
    rating: 4.5,
    reviewCount: 38,
    image: "https://placehold.co/600x600/1E1A1A/CC5555?text=Clips",
    description: "Set of 4 clean cable clips to keep desk cables neat and routed. Adhesive-compatible flat base.",
    featured: false,
  },
  {
    id: 8,
    name: "Botanical Bookmark Set",
    category: "Bookmarks",
    price: 7.00,
    oldPrice: null,
    rating: 4.9,
    reviewCount: 27,
    image: "https://placehold.co/600x600/1C1A24/9B59B6?text=Bookmarks",
    description: "Set of 3 delicate leaf-shaped bookmarks. Thin, elegant, and printed in beautiful detail.",
    featured: false,
  },
  {
    id: 9,
    name: "Mini Fidget Infinity Cube",
    category: "Fidgets",
    price: 11.00,
    oldPrice: 14.00,
    rating: 4.7,
    reviewCount: 44,
    image: "https://placehold.co/600x600/1A2A1A/00C896?text=Cube",
    description: "Compact infinity cube fidget toy with smooth folding action. Quiet and pocket-friendly.",
    featured: false,
  },
  {
    id: 10,
    name: "Tabletop Dice Tower",
    category: "Desk Toys",
    price: 16.00,
    oldPrice: null,
    rating: 4.8,
    reviewCount: 15,
    image: "https://placehold.co/600x600/221A0A/C8842A?text=Dice+Tower",
    description: "Modular dice tower for tabletop RPGs and board games. Includes landing tray. Fits standard dice.",
    featured: true,
  },
  {
    id: 11,
    name: "Headphone Stand",
    category: "Desk Toys",
    price: 13.00,
    oldPrice: 16.00,
    rating: 4.6,
    reviewCount: 33,
    image: "https://placehold.co/600x600/221A0A/C8842A?text=Headphones",
    description: "Sturdy minimalist headphone stand for any desk. Fits over-ear and on-ear headsets.",
    featured: false,
  },
  {
    id: 12,
    name: "Adhesive Wall Hook",
    category: "Home Decor",
    price: 4.00,
    oldPrice: null,
    rating: 4.4,
    reviewCount: 61,
    image: "https://placehold.co/600x600/1E1A1A/CC5555?text=Hook",
    description: "Clean minimal wall hook. Flat base fits command strips (not included). Available in several colours.",
    featured: false,
  },
  {
    id: 13,
    name: "Custom Name Tag Badge",
    category: "Name Tags",
    price: 5.00,
    oldPrice: null,
    rating: 5.0,
    reviewCount: 12,
    image: "https://placehold.co/600x600/22221A/C8C82A?text=Name+Tag",
    description: "Flat printed name tag for events or work. Pin attachment included. Specify your name and colour.",
    featured: false,
  },
  {
    id: 14,
    name: "Mini Dragon Keychain",
    category: "Keychains",
    price: 7.00,
    oldPrice: null,
    rating: 4.9,
    reviewCount: 29,
    image: "https://placehold.co/600x600/1A1A2A/7C6FCD?text=Dragon+Key",
    description: "Tiny articulated dragon on a keychain ring. A little piece of magic for your keys or backpack.",
    featured: true,
  },
  {
    id: 15,
    name: "Herb Planter Tray (Set of 3)",
    category: "Planters",
    price: 15.00,
    oldPrice: 19.00,
    rating: 4.7,
    reviewCount: 9,
    image: "https://placehold.co/600x600/1A241A/4CAF50?text=Herb+Tray",
    description: "Set of 3 connected herb planters for windowsill growing. Drainage holes and a clean modern look.",
    featured: false,
  },
  {
    id: 16,
    name: "Kids Animal Print Set",
    category: "Kids Items",
    price: 12.00,
    oldPrice: null,
    rating: 4.8,
    reviewCount: 18,
    image: "https://placehold.co/600x600/2A1A1A/E05555?text=Animals",
    description: "Set of 3 cute animals — elephant, turtle, frog. Smooth rounded edges, safe for little hands.",
    featured: false,
  },
  {
    id: 17,
    name: "Geometric Bookend Pair",
    category: "Home Decor",
    price: 16.00,
    oldPrice: null,
    rating: 4.6,
    reviewCount: 7,
    image: "https://placehold.co/600x600/1C1A24/9B59B6?text=Bookend",
    description: "Pair of low-poly geometric bookends. Weighted base, sturdy build, minimalist design.",
    featured: false,
  },
  {
    id: 18,
    name: "Articulated Snake",
    category: "Fidgets",
    price: 9.00,
    oldPrice: 11.00,
    rating: 4.8,
    reviewCount: 36,
    image: "https://placehold.co/600x600/1A2A1A/00C896?text=Snake",
    description: "Smooth wave-articulated snake toy. Oddly satisfying to hold and ripple. Great for focus.",
    featured: true,
  },
  {
    id: 19,
    name: "Flexi Octopus",
    category: "Collectibles",
    price: 15.00,
    oldPrice: null,
    rating: 5.0,
    reviewCount: 21,
    image: "./assets/images/3dprinting-image2.png",
    description: "Eight fully articulated tentacles printed in one piece. No assembly needed. A crowd favourite.",
    featured: true,
  },
  {
    id: 20,
    name: "Geometric Lamp Shade",
    category: "Home Decor",
    price: 22.00,
    oldPrice: 28.00,
    rating: 4.8,
    reviewCount: 14,
    image: "https://placehold.co/600x600/1A1A2A/7C6FCD?text=Lamp",
    description: "Low-poly geometric lamp shade for E27 bulbs. Casts beautiful patterned light across the room.",
    featured: true,
  },
  {
    id: 21,
    name: "Phone Grip Ring",
    category: "Phone Stands",
    price: 5.00,
    oldPrice: null,
    rating: 4.6,
    reviewCount: 39,
    image: "https://placehold.co/600x600/1A2A2A/00C896?text=Grip",
    description: "Slim adhesive phone grip ring. Folds flat, holds securely. Available in multiple colours.",
    featured: false,
  },
  {
    id: 22,
    name: "Miniature Chess Set",
    category: "Desk Toys",
    price: 28.00,
    oldPrice: 35.00,
    rating: 4.9,
    reviewCount: 8,
    image: "https://placehold.co/600x600/1E1E1E/AAAAAA?text=Chess",
    description: "Full miniature chess set with board stand. Each piece individually printed with fine detail.",
    featured: true,
  },
  {
    id: 23,
    name: "Cable Tidy Clip Set (x6)",
    category: "Home Decor",
    price: 6.00,
    oldPrice: null,
    rating: 4.5,
    reviewCount: 52,
    image: "https://placehold.co/600x600/1E1A1A/CC5555?text=Clips",
    description: "Six adhesive-backed cable clips to keep your desk tidy. Fits cables up to 6mm wide.",
    featured: false,
  },
  {
    id: 24,
    name: "Succulent Planter Trio",
    category: "Planters",
    price: 14.00,
    oldPrice: null,
    rating: 4.7,
    reviewCount: 17,
    image: "https://placehold.co/600x600/1A241A/4CAF50?text=Planters",
    description: "Set of 3 angular mini planters, perfect for succulents or cacti. Drainage holes included.",
    featured: false,
  },
  {
    id: 25,
    name: "Custom Pet Name Tag",
    category: "Keychains",
    price: 5.00,
    oldPrice: null,
    rating: 5.0,
    reviewCount: 33,
    image: "https://placehold.co/600x600/1A1A2E/5C8DFF?text=Pet+Tag",
    description: "Personalised pet ID tag with your pet's name and your number. Bone or circle shape available.",
    featured: false,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Categories — shown as filter chips on the homepage.
// "All" must remain first. Add/remove categories to match your product range.
// ─────────────────────────────────────────────────────────────────────────────

export const categories = [
  "All",
  "Collectibles",
  "Fidgets",
  "Keychains",
  "Desk Toys",
  "Planters",
  "Home Decor",
  "Bookmarks",
  "Phone Stands",
  "Name Tags",
  "Kids Items",
];
